const DISPLAY_LABELS: Record<string, string> = {
  draft: "Nháp",
  active: "Hoạt động",
  inactive: "Tạm ẩn",
  archived: "Lưu trữ",
  out_of_stock: "Hết hàng",
  blocked: "Bị chặn",
  pending: "Chờ xử lý",
  paid: "Đã thanh toán",
  processing: "Đang xử lý",
  assigned: "Đã gán",
  delivered: "Đã giao",
  completed: "Hoàn tất",
  cancelled: "Đã hủy",
  failed: "Thất bại",
  refunded: "Đã hoàn tiền",
  waiting_payment: "Chờ thanh toán",
  paid_waiting_admin: "Đã thanh toán, chờ admin",
  available: "Khả dụng",
  full: "Đủ slot",
  replaced: "Đã thay thế",
  disabled: "Đã vô hiệu hóa",
  expired: "Hết hạn",
  invalid: "Không hợp lệ",
  open: "Đang mở",
  closed: "Đã đóng",
  waiting_admin: "Chờ admin",
  waiting_customer: "Chờ khách hàng",
  resolved: "Đã xử lý xong",
  rejected: "Từ chối",
  cannot_login: "Không thể đăng nhập",
  wrong_password: "Sai mật khẩu",
  key_invalid: "Key không hợp lệ",
  premium_missing: "Thiếu premium",
  account_limited: "Tài khoản bị giới hạn",
  need_instruction: "Cần hướng dẫn",
  other: "Khác",
  not_ordered: "Chưa đặt",
  ordered: "Đã đặt",
  waiting_source: "Chờ nguồn",
  source_delivered: "Nguồn đã giao",
  source_failed: "Nguồn lỗi",
  claimed_warranty: "Đã claim bảo hành",
  internal: "Nội bộ",
  website: "Website",
  facebook: "Facebook",
  email: "Email",
  phone: "Điện thoại",
  telegram: "Telegram",
  discord: "Discord",
  dedicated: "Riêng",
  shared: "Dùng chung",
  customer_account_upgrade: "Nâng cấp chính chủ",
  dedicated_account: "Tài khoản riêng",
  shared_account: "Tài khoản dùng chung",
  license_key: "Key/License",
  manual_delivery: "Giao thủ công",
  admin_view_secret: "Admin xem secret",
};

export function getDisplayLabel(value: string | null | undefined) {
  if (!value) return "-";

  const normalizedValue = value.toLowerCase();
  return DISPLAY_LABELS[normalizedValue] ?? value;
}
